const specialHealthCareaAreaMapping = {
  'HUS': 'HYKS',
  'Etelä-Karjala': 'HYKS',
  'Kymenlaakso': 'HYKS',
  'Päijät-Häme': 'HYKS',
  'Pohjois-Savo': 'KYS',
  'Etelä-Savo': 'KYS',
  'Itä-Savo': 'KYS',
  'Keski-Suomi': 'KYS',
  'Pohjois-Karjala': 'OYS',
  'Pohjois-Pohjanmaa': 'OYS',
  'Kainuu': 'OYS',
  'Keski-Pohjanmaa': 'OYS',
  'Lappi': 'OYS',
  'Länsi-Pohja': 'OYS',
  'Pirkanmaa': 'TAYS',
  'Etelä-Pohjanmaa': 'TAYS',
  'Kanta-Häme': 'TAYS',
  'Varsinais-Suomi': 'TYKS',
  'Satakunta': 'TYKS',
  'Vaasa': 'TYKS',
  'Ahvenanmaa': 'Ahvenanmaa',
}